package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfVchOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.ORDER_DETAIL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String orderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String orderCharges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.BANK_MARE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String bankMare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.PAYMENT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String ticketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.TICKET_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String ticketCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String ticketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String driveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.BILL_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.BILL_MONEY
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private BigDecimal billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.OPR_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String oprNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.OPR_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String oprDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.RECVERSION
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private Integer recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.DEPT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private BigDecimal overdueFine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.NODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String printTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String uploadRltFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String uploadRltDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String chkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.BAT_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String batDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String chkActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String preActSerial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.PKID
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.PKID
     *
     * @param pkid the value for FIS.FS_LTF_VCH_OUT.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_NO
     *
     * @param orderNo the value for FIS.FS_LTF_VCH_OUT.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.TRANS_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.TRANS_TIME
     *
     * @param transTime the value for FIS.FS_LTF_VCH_OUT.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTransTime(String transTime) {
        this.transTime = transTime == null ? null : transTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_DETAIL
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.ORDER_DETAIL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_DETAIL
     *
     * @param orderDetail the value for FIS.FS_LTF_VCH_OUT.ORDER_DETAIL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail == null ? null : orderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_CHARGES
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOrderCharges() {
        return orderCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.ORDER_CHARGES
     *
     * @param orderCharges the value for FIS.FS_LTF_VCH_OUT.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOrderCharges(String orderCharges) {
        this.orderCharges = orderCharges == null ? null : orderCharges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.BANK_MARE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.BANK_MARE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getBankMare() {
        return bankMare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.BANK_MARE
     *
     * @param bankMare the value for FIS.FS_LTF_VCH_OUT.BANK_MARE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBankMare(String bankMare) {
        this.bankMare = bankMare == null ? null : bankMare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.PAYMENT
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.PAYMENT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.PAYMENT
     *
     * @param payment the value for FIS.FS_LTF_VCH_OUT.PAYMENT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_NO
     *
     * @param ticketNo the value for FIS.FS_LTF_VCH_OUT.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_CODE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.TICKET_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTicketCode() {
        return ticketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_CODE
     *
     * @param ticketCode the value for FIS.FS_LTF_VCH_OUT.TICKET_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode == null ? null : ticketCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.TICKET_TIME
     *
     * @param ticketTime the value for FIS.FS_LTF_VCH_OUT.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTicketTime(String ticketTime) {
        this.ticketTime = ticketTime == null ? null : ticketTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.DRIVE_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getDriveNo() {
        return driveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.DRIVE_NO
     *
     * @param driveNo the value for FIS.FS_LTF_VCH_OUT.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setDriveNo(String driveNo) {
        this.driveNo = driveNo == null ? null : driveNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.PAYER_NAME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.PAYER_NAME
     *
     * @param payerName the value for FIS.FS_LTF_VCH_OUT.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.BILL_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.BILL_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.BILL_NO
     *
     * @param billNo the value for FIS.FS_LTF_VCH_OUT.BILL_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.BILL_MONEY
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.BILL_MONEY
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public BigDecimal getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.BILL_MONEY
     *
     * @param billMoney the value for FIS.FS_LTF_VCH_OUT.BILL_MONEY
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBillMoney(BigDecimal billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.BRANCH_ID
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.BRANCH_ID
     *
     * @param branchId the value for FIS.FS_LTF_VCH_OUT.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.OPR_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.OPR_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOprNo() {
        return oprNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.OPR_NO
     *
     * @param oprNo the value for FIS.FS_LTF_VCH_OUT.OPR_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOprNo(String oprNo) {
        this.oprNo = oprNo == null ? null : oprNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.OPR_DATE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.OPR_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.OPR_DATE
     *
     * @param oprDate the value for FIS.FS_LTF_VCH_OUT.OPR_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOprDate(String oprDate) {
        this.oprDate = oprDate == null ? null : oprDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.REMARK
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.REMARK
     *
     * @param remark the value for FIS.FS_LTF_VCH_OUT.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.RECVERSION
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.RECVERSION
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.RECVERSION
     *
     * @param recversion the value for FIS.FS_LTF_VCH_OUT.RECVERSION
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.DEPT
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.DEPT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.DEPT
     *
     * @param dept the value for FIS.FS_LTF_VCH_OUT.DEPT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.OVERDUE_FINE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public BigDecimal getOverdueFine() {
        return overdueFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.OVERDUE_FINE
     *
     * @param overdueFine the value for FIS.FS_LTF_VCH_OUT.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOverdueFine(BigDecimal overdueFine) {
        this.overdueFine = overdueFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.NODE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.NODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.NODE
     *
     * @param node the value for FIS.FS_LTF_VCH_OUT.NODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.PRINT_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPrintTime() {
        return printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.PRINT_TIME
     *
     * @param printTime the value for FIS.FS_LTF_VCH_OUT.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPrintTime(String printTime) {
        this.printTime = printTime == null ? null : printTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_FLAG
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getUploadRltFlag() {
        return uploadRltFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_FLAG
     *
     * @param uploadRltFlag the value for FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setUploadRltFlag(String uploadRltFlag) {
        this.uploadRltFlag = uploadRltFlag == null ? null : uploadRltFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_DESC
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getUploadRltDesc() {
        return uploadRltDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_DESC
     *
     * @param uploadRltDesc the value for FIS.FS_LTF_VCH_OUT.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setUploadRltDesc(String uploadRltDesc) {
        this.uploadRltDesc = uploadRltDesc == null ? null : uploadRltDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.AREA_CODE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_LTF_VCH_OUT.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.CHK_FLAG
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getChkFlag() {
        return chkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.CHK_FLAG
     *
     * @param chkFlag the value for FIS.FS_LTF_VCH_OUT.CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setChkFlag(String chkFlag) {
        this.chkFlag = chkFlag == null ? null : chkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.BAT_DATE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.BAT_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getBatDate() {
        return batDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.BAT_DATE
     *
     * @param batDate the value for FIS.FS_LTF_VCH_OUT.BAT_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBatDate(String batDate) {
        this.batDate = batDate == null ? null : batDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.CHK_ACT_DT
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getChkActDt() {
        return chkActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.CHK_ACT_DT
     *
     * @param chkActDt the value for FIS.FS_LTF_VCH_OUT.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setChkActDt(String chkActDt) {
        this.chkActDt = chkActDt == null ? null : chkActDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT.PRE_ACT_SERIAL
     *
     * @return the value of FIS.FS_LTF_VCH_OUT.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPreActSerial() {
        return preActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT.PRE_ACT_SERIAL
     *
     * @param preActSerial the value for FIS.FS_LTF_VCH_OUT.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPreActSerial(String preActSerial) {
        this.preActSerial = preActSerial == null ? null : preActSerial.trim();
    }
}