package org.fbi.ltf.repository.model;

public class FsLtfOrgComp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.ORG_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.AREA_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.AREA_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.BANK_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.ORG_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.ORG_ADDR
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String orgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.ORG_TELE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String orgTele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.DEPT_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.REMARK
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.IS_NET
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String isNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.BRANCH_ID
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.OPR_NO
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String oprNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ORG_COMP.OPR_DATE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    private String oprDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.ORG_CODE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.ORG_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.ORG_CODE
     *
     * @param orgCode the value for FIS.FS_LTF_ORG_COMP.ORG_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.AREA_CODE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.AREA_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_LTF_ORG_COMP.AREA_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.AREA_NAME
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.AREA_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.AREA_NAME
     *
     * @param areaName the value for FIS.FS_LTF_ORG_COMP.AREA_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.BANK_CODE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.BANK_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.BANK_CODE
     *
     * @param bankCode the value for FIS.FS_LTF_ORG_COMP.BANK_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.ORG_NAME
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.ORG_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.ORG_NAME
     *
     * @param orgName the value for FIS.FS_LTF_ORG_COMP.ORG_NAME
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.ORG_ADDR
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.ORG_ADDR
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOrgAddr() {
        return orgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.ORG_ADDR
     *
     * @param orgAddr the value for FIS.FS_LTF_ORG_COMP.ORG_ADDR
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOrgAddr(String orgAddr) {
        this.orgAddr = orgAddr == null ? null : orgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.ORG_TELE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.ORG_TELE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOrgTele() {
        return orgTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.ORG_TELE
     *
     * @param orgTele the value for FIS.FS_LTF_ORG_COMP.ORG_TELE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOrgTele(String orgTele) {
        this.orgTele = orgTele == null ? null : orgTele.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.DEPT_CODE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.DEPT_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.DEPT_CODE
     *
     * @param deptCode the value for FIS.FS_LTF_ORG_COMP.DEPT_CODE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.REMARK
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.REMARK
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.REMARK
     *
     * @param remark the value for FIS.FS_LTF_ORG_COMP.REMARK
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.IS_NET
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.IS_NET
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getIsNet() {
        return isNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.IS_NET
     *
     * @param isNet the value for FIS.FS_LTF_ORG_COMP.IS_NET
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setIsNet(String isNet) {
        this.isNet = isNet == null ? null : isNet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.BRANCH_ID
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.BRANCH_ID
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.BRANCH_ID
     *
     * @param branchId the value for FIS.FS_LTF_ORG_COMP.BRANCH_ID
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.OPR_NO
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.OPR_NO
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOprNo() {
        return oprNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.OPR_NO
     *
     * @param oprNo the value for FIS.FS_LTF_ORG_COMP.OPR_NO
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOprNo(String oprNo) {
        this.oprNo = oprNo == null ? null : oprNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ORG_COMP.OPR_DATE
     *
     * @return the value of FIS.FS_LTF_ORG_COMP.OPR_DATE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public String getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ORG_COMP.OPR_DATE
     *
     * @param oprDate the value for FIS.FS_LTF_ORG_COMP.OPR_DATE
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    public void setOprDate(String oprDate) {
        this.oprDate = oprDate == null ? null : oprDate.trim();
    }
}