package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfChkTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.PKID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.TXN_DATE
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.SEND_SYS_ID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String sendSysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.ACTNO
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String actno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.TXNAMT
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private BigDecimal txnamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.DC_FLAG
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String dcFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.MSG_SN
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String msgSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.CHKSTS
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private String chksts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHK_TXN.ACTBAL
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    private BigDecimal actbal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.PKID
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.PKID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.PKID
     *
     * @param pkid the value for FIS.FS_LTF_CHK_TXN.PKID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.TXN_DATE
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.TXN_DATE
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.TXN_DATE
     *
     * @param txnDate the value for FIS.FS_LTF_CHK_TXN.TXN_DATE
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.SEND_SYS_ID
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.SEND_SYS_ID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getSendSysId() {
        return sendSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.SEND_SYS_ID
     *
     * @param sendSysId the value for FIS.FS_LTF_CHK_TXN.SEND_SYS_ID
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setSendSysId(String sendSysId) {
        this.sendSysId = sendSysId == null ? null : sendSysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.ACTNO
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.ACTNO
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getActno() {
        return actno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.ACTNO
     *
     * @param actno the value for FIS.FS_LTF_CHK_TXN.ACTNO
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setActno(String actno) {
        this.actno = actno == null ? null : actno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.TXNAMT
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.TXNAMT
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public BigDecimal getTxnamt() {
        return txnamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.TXNAMT
     *
     * @param txnamt the value for FIS.FS_LTF_CHK_TXN.TXNAMT
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setTxnamt(BigDecimal txnamt) {
        this.txnamt = txnamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.DC_FLAG
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.DC_FLAG
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getDcFlag() {
        return dcFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.DC_FLAG
     *
     * @param dcFlag the value for FIS.FS_LTF_CHK_TXN.DC_FLAG
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setDcFlag(String dcFlag) {
        this.dcFlag = dcFlag == null ? null : dcFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.MSG_SN
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.MSG_SN
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getMsgSn() {
        return msgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.MSG_SN
     *
     * @param msgSn the value for FIS.FS_LTF_CHK_TXN.MSG_SN
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setMsgSn(String msgSn) {
        this.msgSn = msgSn == null ? null : msgSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.CHKSTS
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.CHKSTS
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public String getChksts() {
        return chksts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.CHKSTS
     *
     * @param chksts the value for FIS.FS_LTF_CHK_TXN.CHKSTS
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setChksts(String chksts) {
        this.chksts = chksts == null ? null : chksts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHK_TXN.ACTBAL
     *
     * @return the value of FIS.FS_LTF_CHK_TXN.ACTBAL
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public BigDecimal getActbal() {
        return actbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHK_TXN.ACTBAL
     *
     * @param actbal the value for FIS.FS_LTF_CHK_TXN.ACTBAL
     *
     * @mbggenerated Fri Feb 09 11:09:42 CST 2018
     */
    public void setActbal(BigDecimal actbal) {
        this.actbal = actbal;
    }
}