package org.fbi.ltf.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsLtfChkActExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public FsLtfChkActExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIsNull() {
            addCriterion("SEND_SYS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIsNotNull() {
            addCriterion("SEND_SYS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSendSysIdEqualTo(String value) {
            addCriterion("SEND_SYS_ID =", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotEqualTo(String value) {
            addCriterion("SEND_SYS_ID <>", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdGreaterThan(String value) {
            addCriterion("SEND_SYS_ID >", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_SYS_ID >=", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLessThan(String value) {
            addCriterion("SEND_SYS_ID <", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLessThanOrEqualTo(String value) {
            addCriterion("SEND_SYS_ID <=", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLike(String value) {
            addCriterion("SEND_SYS_ID like", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotLike(String value) {
            addCriterion("SEND_SYS_ID not like", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIn(List<String> values) {
            addCriterion("SEND_SYS_ID in", values, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotIn(List<String> values) {
            addCriterion("SEND_SYS_ID not in", values, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdBetween(String value1, String value2) {
            addCriterion("SEND_SYS_ID between", value1, value2, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotBetween(String value1, String value2) {
            addCriterion("SEND_SYS_ID not between", value1, value2, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andActAmtIsNull() {
            addCriterion("ACT_AMT is null");
            return (Criteria) this;
        }

        public Criteria andActAmtIsNotNull() {
            addCriterion("ACT_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andActAmtEqualTo(BigDecimal value) {
            addCriterion("ACT_AMT =", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtNotEqualTo(BigDecimal value) {
            addCriterion("ACT_AMT <>", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtGreaterThan(BigDecimal value) {
            addCriterion("ACT_AMT >", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_AMT >=", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtLessThan(BigDecimal value) {
            addCriterion("ACT_AMT <", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_AMT <=", value, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtIn(List<BigDecimal> values) {
            addCriterion("ACT_AMT in", values, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtNotIn(List<BigDecimal> values) {
            addCriterion("ACT_AMT not in", values, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_AMT between", value1, value2, "actAmt");
            return (Criteria) this;
        }

        public Criteria andActAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_AMT not between", value1, value2, "actAmt");
            return (Criteria) this;
        }

        public Criteria andChkstsIsNull() {
            addCriterion("CHKSTS is null");
            return (Criteria) this;
        }

        public Criteria andChkstsIsNotNull() {
            addCriterion("CHKSTS is not null");
            return (Criteria) this;
        }

        public Criteria andChkstsEqualTo(String value) {
            addCriterion("CHKSTS =", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotEqualTo(String value) {
            addCriterion("CHKSTS <>", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsGreaterThan(String value) {
            addCriterion("CHKSTS >", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsGreaterThanOrEqualTo(String value) {
            addCriterion("CHKSTS >=", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLessThan(String value) {
            addCriterion("CHKSTS <", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLessThanOrEqualTo(String value) {
            addCriterion("CHKSTS <=", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLike(String value) {
            addCriterion("CHKSTS like", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotLike(String value) {
            addCriterion("CHKSTS not like", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsIn(List<String> values) {
            addCriterion("CHKSTS in", values, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotIn(List<String> values) {
            addCriterion("CHKSTS not in", values, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsBetween(String value1, String value2) {
            addCriterion("CHKSTS between", value1, value2, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotBetween(String value1, String value2) {
            addCriterion("CHKSTS not between", value1, value2, "chksts");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("ORDER_NUM is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("ORDER_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(String value) {
            addCriterion("ORDER_NUM =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(String value) {
            addCriterion("ORDER_NUM <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(String value) {
            addCriterion("ORDER_NUM >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(String value) {
            addCriterion("ORDER_NUM <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLike(String value) {
            addCriterion("ORDER_NUM like", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotLike(String value) {
            addCriterion("ORDER_NUM not like", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<String> values) {
            addCriterion("ORDER_NUM in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<String> values) {
            addCriterion("ORDER_NUM not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(String value1, String value2) {
            addCriterion("ORDER_NUM between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(String value1, String value2) {
            addCriterion("ORDER_NUM not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("REMARK2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("REMARK2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("REMARK2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("REMARK2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("REMARK2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("REMARK2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("REMARK2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("REMARK2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("REMARK2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("REMARK2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("REMARK2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("REMARK2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("REMARK2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andOprDateIsNull() {
            addCriterion("OPR_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOprDateIsNotNull() {
            addCriterion("OPR_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOprDateEqualTo(String value) {
            addCriterion("OPR_DATE =", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotEqualTo(String value) {
            addCriterion("OPR_DATE <>", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateGreaterThan(String value) {
            addCriterion("OPR_DATE >", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPR_DATE >=", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLessThan(String value) {
            addCriterion("OPR_DATE <", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLessThanOrEqualTo(String value) {
            addCriterion("OPR_DATE <=", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLike(String value) {
            addCriterion("OPR_DATE like", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotLike(String value) {
            addCriterion("OPR_DATE not like", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateIn(List<String> values) {
            addCriterion("OPR_DATE in", values, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotIn(List<String> values) {
            addCriterion("OPR_DATE not in", values, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateBetween(String value1, String value2) {
            addCriterion("OPR_DATE between", value1, value2, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotBetween(String value1, String value2) {
            addCriterion("OPR_DATE not between", value1, value2, "oprDate");
            return (Criteria) this;
        }

        public Criteria andSerNumIsNull() {
            addCriterion("SER_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSerNumIsNotNull() {
            addCriterion("SER_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSerNumEqualTo(String value) {
            addCriterion("SER_NUM =", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumNotEqualTo(String value) {
            addCriterion("SER_NUM <>", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumGreaterThan(String value) {
            addCriterion("SER_NUM >", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumGreaterThanOrEqualTo(String value) {
            addCriterion("SER_NUM >=", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumLessThan(String value) {
            addCriterion("SER_NUM <", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumLessThanOrEqualTo(String value) {
            addCriterion("SER_NUM <=", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumLike(String value) {
            addCriterion("SER_NUM like", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumNotLike(String value) {
            addCriterion("SER_NUM not like", value, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumIn(List<String> values) {
            addCriterion("SER_NUM in", values, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumNotIn(List<String> values) {
            addCriterion("SER_NUM not in", values, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumBetween(String value1, String value2) {
            addCriterion("SER_NUM between", value1, value2, "serNum");
            return (Criteria) this;
        }

        public Criteria andSerNumNotBetween(String value1, String value2) {
            addCriterion("SER_NUM not between", value1, value2, "serNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 16 23:33:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_CHK_ACT
     *
     * @mbggenerated Sat Jan 16 23:33:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}