package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfAcctDeal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.ENTP_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String entpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.TX_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String txCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.OUT_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String outAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.IN_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String inAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.TX_AMT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private BigDecimal txAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.IN_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.OUT_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String outOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String cbsActSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.TX_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String txDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String chkActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.ORG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String org;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String preActSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.TX_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String txFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.RESERVE1
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.RESERVE2
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.RESERVE3
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.OPER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String operNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_ACCT_DEAL.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    private String branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.PKID
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.PKID
     *
     * @param pkid the value for FIS.FS_LTF_ACCT_DEAL.PKID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.ENTP_NO
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.ENTP_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getEntpNo() {
        return entpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.ENTP_NO
     *
     * @param entpNo the value for FIS.FS_LTF_ACCT_DEAL.ENTP_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setEntpNo(String entpNo) {
        this.entpNo = entpNo == null ? null : entpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_CODE
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.TX_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTxCode() {
        return txCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_CODE
     *
     * @param txCode the value for FIS.FS_LTF_ACCT_DEAL.TX_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTxCode(String txCode) {
        this.txCode = txCode == null ? null : txCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.OUT_ACCT_NO
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.OUT_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOutAcctNo() {
        return outAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.OUT_ACCT_NO
     *
     * @param outAcctNo the value for FIS.FS_LTF_ACCT_DEAL.OUT_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOutAcctNo(String outAcctNo) {
        this.outAcctNo = outAcctNo == null ? null : outAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.IN_ACCT_NO
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.IN_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getInAcctNo() {
        return inAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.IN_ACCT_NO
     *
     * @param inAcctNo the value for FIS.FS_LTF_ACCT_DEAL.IN_ACCT_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setInAcctNo(String inAcctNo) {
        this.inAcctNo = inAcctNo == null ? null : inAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_AMT
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.TX_AMT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public BigDecimal getTxAmt() {
        return txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_AMT
     *
     * @param txAmt the value for FIS.FS_LTF_ACCT_DEAL.TX_AMT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTxAmt(BigDecimal txAmt) {
        this.txAmt = txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.IN_ORG_CODE
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.IN_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getInOrgCode() {
        return inOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.IN_ORG_CODE
     *
     * @param inOrgCode the value for FIS.FS_LTF_ACCT_DEAL.IN_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode == null ? null : inOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.OUT_ORG_CODE
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.OUT_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOutOrgCode() {
        return outOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.OUT_ORG_CODE
     *
     * @param outOrgCode the value for FIS.FS_LTF_ACCT_DEAL.OUT_ORG_CODE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOutOrgCode(String outOrgCode) {
        this.outOrgCode = outOrgCode == null ? null : outOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.CBS_ACT_SERIAL
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getCbsActSerial() {
        return cbsActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.CBS_ACT_SERIAL
     *
     * @param cbsActSerial the value for FIS.FS_LTF_ACCT_DEAL.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setCbsActSerial(String cbsActSerial) {
        this.cbsActSerial = cbsActSerial == null ? null : cbsActSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_DATE
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.TX_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTxDate() {
        return txDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_DATE
     *
     * @param txDate the value for FIS.FS_LTF_ACCT_DEAL.TX_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTxDate(String txDate) {
        this.txDate = txDate == null ? null : txDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.CHK_ACT_DT
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getChkActDt() {
        return chkActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.CHK_ACT_DT
     *
     * @param chkActDt the value for FIS.FS_LTF_ACCT_DEAL.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setChkActDt(String chkActDt) {
        this.chkActDt = chkActDt == null ? null : chkActDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.ORG
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.ORG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.ORG
     *
     * @param org the value for FIS.FS_LTF_ACCT_DEAL.ORG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOrg(String org) {
        this.org = org == null ? null : org.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.PRE_ACT_SERIAL
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getPreActSerial() {
        return preActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.PRE_ACT_SERIAL
     *
     * @param preActSerial the value for FIS.FS_LTF_ACCT_DEAL.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setPreActSerial(String preActSerial) {
        this.preActSerial = preActSerial == null ? null : preActSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_FLAG
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.TX_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getTxFlag() {
        return txFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.TX_FLAG
     *
     * @param txFlag the value for FIS.FS_LTF_ACCT_DEAL.TX_FLAG
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setTxFlag(String txFlag) {
        this.txFlag = txFlag == null ? null : txFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.REMARK
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.REMARK
     *
     * @param remark the value for FIS.FS_LTF_ACCT_DEAL.REMARK
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE1
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.RESERVE1
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE1
     *
     * @param reserve1 the value for FIS.FS_LTF_ACCT_DEAL.RESERVE1
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE2
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.RESERVE2
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE2
     *
     * @param reserve2 the value for FIS.FS_LTF_ACCT_DEAL.RESERVE2
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE3
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.RESERVE3
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.RESERVE3
     *
     * @param reserve3 the value for FIS.FS_LTF_ACCT_DEAL.RESERVE3
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.OPER_DATE
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.OPER_DATE
     *
     * @param operDate the value for FIS.FS_LTF_ACCT_DEAL.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.OPER_NO
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.OPER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getOperNo() {
        return operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.OPER_NO
     *
     * @param operNo the value for FIS.FS_LTF_ACCT_DEAL.OPER_NO
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setOperNo(String operNo) {
        this.operNo = operNo == null ? null : operNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_ACCT_DEAL.BRANCH_ID
     *
     * @return the value of FIS.FS_LTF_ACCT_DEAL.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_ACCT_DEAL.BRANCH_ID
     *
     * @param branchId the value for FIS.FS_LTF_ACCT_DEAL.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 10:27:47 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }
}