package org.fbi.ltf.repository.model;

import java.util.ArrayList;
import java.util.List;

public class FsLtfVchJrnlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public FsLtfVchJrnlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andVchCountIsNull() {
            addCriterion("VCH_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andVchCountIsNotNull() {
            addCriterion("VCH_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andVchCountEqualTo(Integer value) {
            addCriterion("VCH_COUNT =", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountNotEqualTo(Integer value) {
            addCriterion("VCH_COUNT <>", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountGreaterThan(Integer value) {
            addCriterion("VCH_COUNT >", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("VCH_COUNT >=", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountLessThan(Integer value) {
            addCriterion("VCH_COUNT <", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountLessThanOrEqualTo(Integer value) {
            addCriterion("VCH_COUNT <=", value, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountIn(List<Integer> values) {
            addCriterion("VCH_COUNT in", values, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountNotIn(List<Integer> values) {
            addCriterion("VCH_COUNT not in", values, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountBetween(Integer value1, Integer value2) {
            addCriterion("VCH_COUNT between", value1, value2, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchCountNotBetween(Integer value1, Integer value2) {
            addCriterion("VCH_COUNT not between", value1, value2, "vchCount");
            return (Criteria) this;
        }

        public Criteria andVchStartNoIsNull() {
            addCriterion("VCH_START_NO is null");
            return (Criteria) this;
        }

        public Criteria andVchStartNoIsNotNull() {
            addCriterion("VCH_START_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVchStartNoEqualTo(String value) {
            addCriterion("VCH_START_NO =", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoNotEqualTo(String value) {
            addCriterion("VCH_START_NO <>", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoGreaterThan(String value) {
            addCriterion("VCH_START_NO >", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_START_NO >=", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoLessThan(String value) {
            addCriterion("VCH_START_NO <", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoLessThanOrEqualTo(String value) {
            addCriterion("VCH_START_NO <=", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoLike(String value) {
            addCriterion("VCH_START_NO like", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoNotLike(String value) {
            addCriterion("VCH_START_NO not like", value, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoIn(List<String> values) {
            addCriterion("VCH_START_NO in", values, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoNotIn(List<String> values) {
            addCriterion("VCH_START_NO not in", values, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoBetween(String value1, String value2) {
            addCriterion("VCH_START_NO between", value1, value2, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchStartNoNotBetween(String value1, String value2) {
            addCriterion("VCH_START_NO not between", value1, value2, "vchStartNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoIsNull() {
            addCriterion("VCH_END_NO is null");
            return (Criteria) this;
        }

        public Criteria andVchEndNoIsNotNull() {
            addCriterion("VCH_END_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVchEndNoEqualTo(String value) {
            addCriterion("VCH_END_NO =", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoNotEqualTo(String value) {
            addCriterion("VCH_END_NO <>", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoGreaterThan(String value) {
            addCriterion("VCH_END_NO >", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_END_NO >=", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoLessThan(String value) {
            addCriterion("VCH_END_NO <", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoLessThanOrEqualTo(String value) {
            addCriterion("VCH_END_NO <=", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoLike(String value) {
            addCriterion("VCH_END_NO like", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoNotLike(String value) {
            addCriterion("VCH_END_NO not like", value, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoIn(List<String> values) {
            addCriterion("VCH_END_NO in", values, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoNotIn(List<String> values) {
            addCriterion("VCH_END_NO not in", values, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoBetween(String value1, String value2) {
            addCriterion("VCH_END_NO between", value1, value2, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchEndNoNotBetween(String value1, String value2) {
            addCriterion("VCH_END_NO not between", value1, value2, "vchEndNo");
            return (Criteria) this;
        }

        public Criteria andVchStateIsNull() {
            addCriterion("VCH_STATE is null");
            return (Criteria) this;
        }

        public Criteria andVchStateIsNotNull() {
            addCriterion("VCH_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andVchStateEqualTo(String value) {
            addCriterion("VCH_STATE =", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateNotEqualTo(String value) {
            addCriterion("VCH_STATE <>", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateGreaterThan(String value) {
            addCriterion("VCH_STATE >", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_STATE >=", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateLessThan(String value) {
            addCriterion("VCH_STATE <", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateLessThanOrEqualTo(String value) {
            addCriterion("VCH_STATE <=", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateLike(String value) {
            addCriterion("VCH_STATE like", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateNotLike(String value) {
            addCriterion("VCH_STATE not like", value, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateIn(List<String> values) {
            addCriterion("VCH_STATE in", values, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateNotIn(List<String> values) {
            addCriterion("VCH_STATE not in", values, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateBetween(String value1, String value2) {
            addCriterion("VCH_STATE between", value1, value2, "vchState");
            return (Criteria) this;
        }

        public Criteria andVchStateNotBetween(String value1, String value2) {
            addCriterion("VCH_STATE not between", value1, value2, "vchState");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(String value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(String value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(String value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(String value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLike(String value) {
            addCriterion("BRANCH_ID like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotLike(String value) {
            addCriterion("BRANCH_ID not like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<String> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<String> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(String value1, String value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andOprNoIsNull() {
            addCriterion("OPR_NO is null");
            return (Criteria) this;
        }

        public Criteria andOprNoIsNotNull() {
            addCriterion("OPR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOprNoEqualTo(String value) {
            addCriterion("OPR_NO =", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoNotEqualTo(String value) {
            addCriterion("OPR_NO <>", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoGreaterThan(String value) {
            addCriterion("OPR_NO >", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoGreaterThanOrEqualTo(String value) {
            addCriterion("OPR_NO >=", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoLessThan(String value) {
            addCriterion("OPR_NO <", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoLessThanOrEqualTo(String value) {
            addCriterion("OPR_NO <=", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoLike(String value) {
            addCriterion("OPR_NO like", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoNotLike(String value) {
            addCriterion("OPR_NO not like", value, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoIn(List<String> values) {
            addCriterion("OPR_NO in", values, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoNotIn(List<String> values) {
            addCriterion("OPR_NO not in", values, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoBetween(String value1, String value2) {
            addCriterion("OPR_NO between", value1, value2, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprNoNotBetween(String value1, String value2) {
            addCriterion("OPR_NO not between", value1, value2, "oprNo");
            return (Criteria) this;
        }

        public Criteria andOprDateIsNull() {
            addCriterion("OPR_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOprDateIsNotNull() {
            addCriterion("OPR_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOprDateEqualTo(String value) {
            addCriterion("OPR_DATE =", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotEqualTo(String value) {
            addCriterion("OPR_DATE <>", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateGreaterThan(String value) {
            addCriterion("OPR_DATE >", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPR_DATE >=", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLessThan(String value) {
            addCriterion("OPR_DATE <", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLessThanOrEqualTo(String value) {
            addCriterion("OPR_DATE <=", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateLike(String value) {
            addCriterion("OPR_DATE like", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotLike(String value) {
            addCriterion("OPR_DATE not like", value, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateIn(List<String> values) {
            addCriterion("OPR_DATE in", values, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotIn(List<String> values) {
            addCriterion("OPR_DATE not in", values, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateBetween(String value1, String value2) {
            addCriterion("OPR_DATE between", value1, value2, "oprDate");
            return (Criteria) this;
        }

        public Criteria andOprDateNotBetween(String value1, String value2) {
            addCriterion("OPR_DATE not between", value1, value2, "oprDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Integer value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Integer value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Integer value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Integer value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Integer> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Integer> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andBusCodeIsNull() {
            addCriterion("BUS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBusCodeIsNotNull() {
            addCriterion("BUS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBusCodeEqualTo(String value) {
            addCriterion("BUS_CODE =", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeNotEqualTo(String value) {
            addCriterion("BUS_CODE <>", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeGreaterThan(String value) {
            addCriterion("BUS_CODE >", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BUS_CODE >=", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeLessThan(String value) {
            addCriterion("BUS_CODE <", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeLessThanOrEqualTo(String value) {
            addCriterion("BUS_CODE <=", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeLike(String value) {
            addCriterion("BUS_CODE like", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeNotLike(String value) {
            addCriterion("BUS_CODE not like", value, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeIn(List<String> values) {
            addCriterion("BUS_CODE in", values, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeNotIn(List<String> values) {
            addCriterion("BUS_CODE not in", values, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeBetween(String value1, String value2) {
            addCriterion("BUS_CODE between", value1, value2, "busCode");
            return (Criteria) this;
        }

        public Criteria andBusCodeNotBetween(String value1, String value2) {
            addCriterion("BUS_CODE not between", value1, value2, "busCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeIsNull() {
            addCriterion("BILL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBillCodeIsNotNull() {
            addCriterion("BILL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBillCodeEqualTo(String value) {
            addCriterion("BILL_CODE =", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeNotEqualTo(String value) {
            addCriterion("BILL_CODE <>", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeGreaterThan(String value) {
            addCriterion("BILL_CODE >", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_CODE >=", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeLessThan(String value) {
            addCriterion("BILL_CODE <", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeLessThanOrEqualTo(String value) {
            addCriterion("BILL_CODE <=", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeLike(String value) {
            addCriterion("BILL_CODE like", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeNotLike(String value) {
            addCriterion("BILL_CODE not like", value, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeIn(List<String> values) {
            addCriterion("BILL_CODE in", values, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeNotIn(List<String> values) {
            addCriterion("BILL_CODE not in", values, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeBetween(String value1, String value2) {
            addCriterion("BILL_CODE between", value1, value2, "billCode");
            return (Criteria) this;
        }

        public Criteria andBillCodeNotBetween(String value1, String value2) {
            addCriterion("BILL_CODE not between", value1, value2, "billCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 13 11:13:33 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_JRNL
     *
     * @mbggenerated Sun Dec 13 11:13:33 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}