package org.fbi.ltf.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsLtfVchDzwcExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public FsLtfVchDzwcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("APP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("APP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("APP_NAME =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("APP_NAME <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("APP_NAME >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("APP_NAME >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("APP_NAME <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("APP_NAME <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("APP_NAME like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("APP_NAME not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("APP_NAME in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("APP_NAME not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("APP_NAME between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("APP_NAME not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNull() {
            addCriterion("TRANS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTransTimeIsNotNull() {
            addCriterion("TRANS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTransTimeEqualTo(Object value) {
            addCriterion("TRANS_TIME =", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotEqualTo(Object value) {
            addCriterion("TRANS_TIME <>", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThan(Object value) {
            addCriterion("TRANS_TIME >", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeGreaterThanOrEqualTo(Object value) {
            addCriterion("TRANS_TIME >=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThan(Object value) {
            addCriterion("TRANS_TIME <", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeLessThanOrEqualTo(Object value) {
            addCriterion("TRANS_TIME <=", value, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeIn(List<Object> values) {
            addCriterion("TRANS_TIME in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotIn(List<Object> values) {
            addCriterion("TRANS_TIME not in", values, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeBetween(Object value1, Object value2) {
            addCriterion("TRANS_TIME between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andTransTimeNotBetween(Object value1, Object value2) {
            addCriterion("TRANS_TIME not between", value1, value2, "transTime");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("AMOUNT =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("AMOUNT >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("AMOUNT <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMOUNT <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("AMOUNT in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("AMOUNT not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMOUNT not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andEditFlagIsNull() {
            addCriterion("EDIT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andEditFlagIsNotNull() {
            addCriterion("EDIT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEditFlagEqualTo(String value) {
            addCriterion("EDIT_FLAG =", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagNotEqualTo(String value) {
            addCriterion("EDIT_FLAG <>", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagGreaterThan(String value) {
            addCriterion("EDIT_FLAG >", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagGreaterThanOrEqualTo(String value) {
            addCriterion("EDIT_FLAG >=", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagLessThan(String value) {
            addCriterion("EDIT_FLAG <", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagLessThanOrEqualTo(String value) {
            addCriterion("EDIT_FLAG <=", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagLike(String value) {
            addCriterion("EDIT_FLAG like", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagNotLike(String value) {
            addCriterion("EDIT_FLAG not like", value, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagIn(List<String> values) {
            addCriterion("EDIT_FLAG in", values, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagNotIn(List<String> values) {
            addCriterion("EDIT_FLAG not in", values, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagBetween(String value1, String value2) {
            addCriterion("EDIT_FLAG between", value1, value2, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditFlagNotBetween(String value1, String value2) {
            addCriterion("EDIT_FLAG not between", value1, value2, "editFlag");
            return (Criteria) this;
        }

        public Criteria andEditStateIsNull() {
            addCriterion("EDIT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andEditStateIsNotNull() {
            addCriterion("EDIT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andEditStateEqualTo(String value) {
            addCriterion("EDIT_STATE =", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateNotEqualTo(String value) {
            addCriterion("EDIT_STATE <>", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateGreaterThan(String value) {
            addCriterion("EDIT_STATE >", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateGreaterThanOrEqualTo(String value) {
            addCriterion("EDIT_STATE >=", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateLessThan(String value) {
            addCriterion("EDIT_STATE <", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateLessThanOrEqualTo(String value) {
            addCriterion("EDIT_STATE <=", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateLike(String value) {
            addCriterion("EDIT_STATE like", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateNotLike(String value) {
            addCriterion("EDIT_STATE not like", value, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateIn(List<String> values) {
            addCriterion("EDIT_STATE in", values, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateNotIn(List<String> values) {
            addCriterion("EDIT_STATE not in", values, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateBetween(String value1, String value2) {
            addCriterion("EDIT_STATE between", value1, value2, "editState");
            return (Criteria) this;
        }

        public Criteria andEditStateNotBetween(String value1, String value2) {
            addCriterion("EDIT_STATE not between", value1, value2, "editState");
            return (Criteria) this;
        }

        public Criteria andNodeIsNull() {
            addCriterion("NODE is null");
            return (Criteria) this;
        }

        public Criteria andNodeIsNotNull() {
            addCriterion("NODE is not null");
            return (Criteria) this;
        }

        public Criteria andNodeEqualTo(String value) {
            addCriterion("NODE =", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotEqualTo(String value) {
            addCriterion("NODE <>", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThan(String value) {
            addCriterion("NODE >", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThanOrEqualTo(String value) {
            addCriterion("NODE >=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThan(String value) {
            addCriterion("NODE <", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThanOrEqualTo(String value) {
            addCriterion("NODE <=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLike(String value) {
            addCriterion("NODE like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotLike(String value) {
            addCriterion("NODE not like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeIn(List<String> values) {
            addCriterion("NODE in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotIn(List<String> values) {
            addCriterion("NODE not in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeBetween(String value1, String value2) {
            addCriterion("NODE between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotBetween(String value1, String value2) {
            addCriterion("NODE not between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(String value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(String value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(String value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(String value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(String value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLike(String value) {
            addCriterion("OPER_DATE like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotLike(String value) {
            addCriterion("OPER_DATE not like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<String> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<String> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(String value1, String value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(String value1, String value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeIsNull() {
            addCriterion("OPERDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeIsNotNull() {
            addCriterion("OPERDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeEqualTo(String value) {
            addCriterion("OPERDATETIME =", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeNotEqualTo(String value) {
            addCriterion("OPERDATETIME <>", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeGreaterThan(String value) {
            addCriterion("OPERDATETIME >", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERDATETIME >=", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeLessThan(String value) {
            addCriterion("OPERDATETIME <", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeLessThanOrEqualTo(String value) {
            addCriterion("OPERDATETIME <=", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeLike(String value) {
            addCriterion("OPERDATETIME like", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeNotLike(String value) {
            addCriterion("OPERDATETIME not like", value, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeIn(List<String> values) {
            addCriterion("OPERDATETIME in", values, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeNotIn(List<String> values) {
            addCriterion("OPERDATETIME not in", values, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeBetween(String value1, String value2) {
            addCriterion("OPERDATETIME between", value1, value2, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andOperdatetimeNotBetween(String value1, String value2) {
            addCriterion("OPERDATETIME not between", value1, value2, "operdatetime");
            return (Criteria) this;
        }

        public Criteria andChkActDtIsNull() {
            addCriterion("CHK_ACT_DT is null");
            return (Criteria) this;
        }

        public Criteria andChkActDtIsNotNull() {
            addCriterion("CHK_ACT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andChkActDtEqualTo(String value) {
            addCriterion("CHK_ACT_DT =", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtNotEqualTo(String value) {
            addCriterion("CHK_ACT_DT <>", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtGreaterThan(String value) {
            addCriterion("CHK_ACT_DT >", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_ACT_DT >=", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtLessThan(String value) {
            addCriterion("CHK_ACT_DT <", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtLessThanOrEqualTo(String value) {
            addCriterion("CHK_ACT_DT <=", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtLike(String value) {
            addCriterion("CHK_ACT_DT like", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtNotLike(String value) {
            addCriterion("CHK_ACT_DT not like", value, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtIn(List<String> values) {
            addCriterion("CHK_ACT_DT in", values, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtNotIn(List<String> values) {
            addCriterion("CHK_ACT_DT not in", values, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtBetween(String value1, String value2) {
            addCriterion("CHK_ACT_DT between", value1, value2, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkActDtNotBetween(String value1, String value2) {
            addCriterion("CHK_ACT_DT not between", value1, value2, "chkActDt");
            return (Criteria) this;
        }

        public Criteria andChkFlagIsNull() {
            addCriterion("CHK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andChkFlagIsNotNull() {
            addCriterion("CHK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andChkFlagEqualTo(String value) {
            addCriterion("CHK_FLAG =", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotEqualTo(String value) {
            addCriterion("CHK_FLAG <>", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagGreaterThan(String value) {
            addCriterion("CHK_FLAG >", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_FLAG >=", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLessThan(String value) {
            addCriterion("CHK_FLAG <", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLessThanOrEqualTo(String value) {
            addCriterion("CHK_FLAG <=", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLike(String value) {
            addCriterion("CHK_FLAG like", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotLike(String value) {
            addCriterion("CHK_FLAG not like", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagIn(List<String> values) {
            addCriterion("CHK_FLAG in", values, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotIn(List<String> values) {
            addCriterion("CHK_FLAG not in", values, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagBetween(String value1, String value2) {
            addCriterion("CHK_FLAG between", value1, value2, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotBetween(String value1, String value2) {
            addCriterion("CHK_FLAG not between", value1, value2, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andRmrkIsNull() {
            addCriterion("RMRK is null");
            return (Criteria) this;
        }

        public Criteria andRmrkIsNotNull() {
            addCriterion("RMRK is not null");
            return (Criteria) this;
        }

        public Criteria andRmrkEqualTo(String value) {
            addCriterion("RMRK =", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotEqualTo(String value) {
            addCriterion("RMRK <>", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkGreaterThan(String value) {
            addCriterion("RMRK >", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkGreaterThanOrEqualTo(String value) {
            addCriterion("RMRK >=", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLessThan(String value) {
            addCriterion("RMRK <", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLessThanOrEqualTo(String value) {
            addCriterion("RMRK <=", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLike(String value) {
            addCriterion("RMRK like", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotLike(String value) {
            addCriterion("RMRK not like", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkIn(List<String> values) {
            addCriterion("RMRK in", values, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotIn(List<String> values) {
            addCriterion("RMRK not in", values, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkBetween(String value1, String value2) {
            addCriterion("RMRK between", value1, value2, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotBetween(String value1, String value2) {
            addCriterion("RMRK not between", value1, value2, "rmrk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 14:22:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_LTF_VCH_DZWC
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}