package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfChargeName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String chargeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String chargeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.IS_CANCEL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String isCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.BUS_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String busCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.AMOUNT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_CHARGE_NAME.TICKET_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String ticketCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_CODE
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.CHARGE_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getChargeCode() {
        return chargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_CODE
     *
     * @param chargeCode the value for FIS.FS_LTF_CHARGE_NAME.CHARGE_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode == null ? null : chargeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_NAME
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.CHARGE_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getChargeName() {
        return chargeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.CHARGE_NAME
     *
     * @param chargeName the value for FIS.FS_LTF_CHARGE_NAME.CHARGE_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setChargeName(String chargeName) {
        this.chargeName = chargeName == null ? null : chargeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.IS_CANCEL
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.IS_CANCEL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getIsCancel() {
        return isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.IS_CANCEL
     *
     * @param isCancel the value for FIS.FS_LTF_CHARGE_NAME.IS_CANCEL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setIsCancel(String isCancel) {
        this.isCancel = isCancel == null ? null : isCancel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.REMARK
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.REMARK
     *
     * @param remark the value for FIS.FS_LTF_CHARGE_NAME.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.BUS_CODE
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.BUS_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getBusCode() {
        return busCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.BUS_CODE
     *
     * @param busCode the value for FIS.FS_LTF_CHARGE_NAME.BUS_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setBusCode(String busCode) {
        this.busCode = busCode == null ? null : busCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.AMOUNT
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.AMOUNT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.AMOUNT
     *
     * @param amount the value for FIS.FS_LTF_CHARGE_NAME.AMOUNT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_CHARGE_NAME.TICKET_CODE
     *
     * @return the value of FIS.FS_LTF_CHARGE_NAME.TICKET_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getTicketCode() {
        return ticketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_CHARGE_NAME.TICKET_CODE
     *
     * @param ticketCode the value for FIS.FS_LTF_CHARGE_NAME.TICKET_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode == null ? null : ticketCode.trim();
    }
}