package org.fbi.ltf.repository.model;

public class FsLtfTpdept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TPDEPT.ORGDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    private String orgdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TPDEPT.NEWDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    private String newdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TPDEPT.DEPT_NAME
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TPDEPT.REMARK
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TPDEPT.ISCANCL
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    private String iscancl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TPDEPT.ORGDEPT
     *
     * @return the value of FIS.FS_LTF_TPDEPT.ORGDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public String getOrgdept() {
        return orgdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TPDEPT.ORGDEPT
     *
     * @param orgdept the value for FIS.FS_LTF_TPDEPT.ORGDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public void setOrgdept(String orgdept) {
        this.orgdept = orgdept == null ? null : orgdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TPDEPT.NEWDEPT
     *
     * @return the value of FIS.FS_LTF_TPDEPT.NEWDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public String getNewdept() {
        return newdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TPDEPT.NEWDEPT
     *
     * @param newdept the value for FIS.FS_LTF_TPDEPT.NEWDEPT
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public void setNewdept(String newdept) {
        this.newdept = newdept == null ? null : newdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TPDEPT.DEPT_NAME
     *
     * @return the value of FIS.FS_LTF_TPDEPT.DEPT_NAME
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TPDEPT.DEPT_NAME
     *
     * @param deptName the value for FIS.FS_LTF_TPDEPT.DEPT_NAME
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TPDEPT.REMARK
     *
     * @return the value of FIS.FS_LTF_TPDEPT.REMARK
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TPDEPT.REMARK
     *
     * @param remark the value for FIS.FS_LTF_TPDEPT.REMARK
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TPDEPT.ISCANCL
     *
     * @return the value of FIS.FS_LTF_TPDEPT.ISCANCL
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public String getIscancl() {
        return iscancl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TPDEPT.ISCANCL
     *
     * @param iscancl the value for FIS.FS_LTF_TPDEPT.ISCANCL
     *
     * @mbggenerated Wed Dec 16 16:48:05 CST 2015
     */
    public void setIscancl(String iscancl) {
        this.iscancl = iscancl == null ? null : iscancl.trim();
    }
}