package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfVchDzwc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.PKID
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.APP_NAME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.ORDER_NO
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.TRANS_TIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private Object transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.AMOUNT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.EDIT_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String editFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.EDIT_STATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String editState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.NODE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.OPER_DATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.OPERDATETIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String operdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.CHK_ACT_DT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String chkActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.CHK_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String chkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_DZWC.RMRK
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    private String rmrk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.PKID
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.PKID
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.PKID
     *
     * @param pkid the value for FIS.FS_LTF_VCH_DZWC.PKID
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.APP_NAME
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.APP_NAME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.APP_NAME
     *
     * @param appName the value for FIS.FS_LTF_VCH_DZWC.APP_NAME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.ORDER_NO
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.ORDER_NO
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.ORDER_NO
     *
     * @param orderNo the value for FIS.FS_LTF_VCH_DZWC.ORDER_NO
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.TRANS_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.TRANS_TIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public Object getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.TRANS_TIME
     *
     * @param transTime the value for FIS.FS_LTF_VCH_DZWC.TRANS_TIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setTransTime(Object transTime) {
        this.transTime = transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.AMOUNT
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.AMOUNT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.AMOUNT
     *
     * @param amount the value for FIS.FS_LTF_VCH_DZWC.AMOUNT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.EDIT_FLAG
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.EDIT_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getEditFlag() {
        return editFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.EDIT_FLAG
     *
     * @param editFlag the value for FIS.FS_LTF_VCH_DZWC.EDIT_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setEditFlag(String editFlag) {
        this.editFlag = editFlag == null ? null : editFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.EDIT_STATE
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.EDIT_STATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getEditState() {
        return editState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.EDIT_STATE
     *
     * @param editState the value for FIS.FS_LTF_VCH_DZWC.EDIT_STATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setEditState(String editState) {
        this.editState = editState == null ? null : editState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.NODE
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.NODE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.NODE
     *
     * @param node the value for FIS.FS_LTF_VCH_DZWC.NODE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.OPER_DATE
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.OPER_DATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.OPER_DATE
     *
     * @param operDate the value for FIS.FS_LTF_VCH_DZWC.OPER_DATE
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.OPERDATETIME
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.OPERDATETIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getOperdatetime() {
        return operdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.OPERDATETIME
     *
     * @param operdatetime the value for FIS.FS_LTF_VCH_DZWC.OPERDATETIME
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setOperdatetime(String operdatetime) {
        this.operdatetime = operdatetime == null ? null : operdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.CHK_ACT_DT
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.CHK_ACT_DT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getChkActDt() {
        return chkActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.CHK_ACT_DT
     *
     * @param chkActDt the value for FIS.FS_LTF_VCH_DZWC.CHK_ACT_DT
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setChkActDt(String chkActDt) {
        this.chkActDt = chkActDt == null ? null : chkActDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.CHK_FLAG
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.CHK_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getChkFlag() {
        return chkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.CHK_FLAG
     *
     * @param chkFlag the value for FIS.FS_LTF_VCH_DZWC.CHK_FLAG
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setChkFlag(String chkFlag) {
        this.chkFlag = chkFlag == null ? null : chkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_DZWC.RMRK
     *
     * @return the value of FIS.FS_LTF_VCH_DZWC.RMRK
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public String getRmrk() {
        return rmrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_DZWC.RMRK
     *
     * @param rmrk the value for FIS.FS_LTF_VCH_DZWC.RMRK
     *
     * @mbggenerated Mon Mar 19 14:22:41 CST 2018
     */
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk == null ? null : rmrk.trim();
    }
}