package org.fbi.ltf.repository.model;

public class FsLtfVchAbnormal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.PKID
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.APP_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.TRANS_TIME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_DETAIL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String orderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.BILL_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE_TYPE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String causeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.NODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CONTENT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String resContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String oprNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_DATE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String oprDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_ABNORMAL.RECVERSION
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    private Integer recversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.PKID
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.PKID
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.PKID
     *
     * @param pkid the value for FIS.FS_LTF_VCH_ABNORMAL.PKID
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.APP_NAME
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.APP_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.APP_NAME
     *
     * @param appName the value for FIS.FS_LTF_VCH_ABNORMAL.APP_NAME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_NO
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.ORDER_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_NO
     *
     * @param orderNo the value for FIS.FS_LTF_VCH_ABNORMAL.ORDER_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.TRANS_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.TRANS_TIME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.TRANS_TIME
     *
     * @param transTime the value for FIS.FS_LTF_VCH_ABNORMAL.TRANS_TIME
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setTransTime(String transTime) {
        this.transTime = transTime == null ? null : transTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_DETAIL
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.ORDER_DETAIL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.ORDER_DETAIL
     *
     * @param orderDetail the value for FIS.FS_LTF_VCH_ABNORMAL.ORDER_DETAIL
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail == null ? null : orderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.BILL_NO
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.BILL_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.BILL_NO
     *
     * @param billNo the value for FIS.FS_LTF_VCH_ABNORMAL.BILL_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE_TYPE
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.CAUSE_TYPE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getCauseType() {
        return causeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE_TYPE
     *
     * @param causeType the value for FIS.FS_LTF_VCH_ABNORMAL.CAUSE_TYPE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setCauseType(String causeType) {
        this.causeType = causeType == null ? null : causeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.CAUSE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.CAUSE
     *
     * @param cause the value for FIS.FS_LTF_VCH_ABNORMAL.CAUSE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.NODE
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.NODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.NODE
     *
     * @param node the value for FIS.FS_LTF_VCH_ABNORMAL.NODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CODE
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.RES_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CODE
     *
     * @param resCode the value for FIS.FS_LTF_VCH_ABNORMAL.RES_CODE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CONTENT
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.RES_CONTENT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getResContent() {
        return resContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RES_CONTENT
     *
     * @param resContent the value for FIS.FS_LTF_VCH_ABNORMAL.RES_CONTENT
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setResContent(String resContent) {
        this.resContent = resContent == null ? null : resContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_NO
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.OPR_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getOprNo() {
        return oprNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_NO
     *
     * @param oprNo the value for FIS.FS_LTF_VCH_ABNORMAL.OPR_NO
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setOprNo(String oprNo) {
        this.oprNo = oprNo == null ? null : oprNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_DATE
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.OPR_DATE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.OPR_DATE
     *
     * @param oprDate the value for FIS.FS_LTF_VCH_ABNORMAL.OPR_DATE
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setOprDate(String oprDate) {
        this.oprDate = oprDate == null ? null : oprDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.REMARK
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.REMARK
     *
     * @param remark the value for FIS.FS_LTF_VCH_ABNORMAL.REMARK
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RECVERSION
     *
     * @return the value of FIS.FS_LTF_VCH_ABNORMAL.RECVERSION
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_ABNORMAL.RECVERSION
     *
     * @param recversion the value for FIS.FS_LTF_VCH_ABNORMAL.RECVERSION
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }
}