package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfTicketInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PKID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BANK_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private BigDecimal overdueFine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BUS_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String busCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String orderCharges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.ACCOUNT_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BILL_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String ticketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String ticketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.TICKET_AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private BigDecimal ticketAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.ID_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PHONE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.HANDLE_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String handleDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String driveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.RUN_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String runNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PLATE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String plateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PLATE_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String plateColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.CAR_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.CAR_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String carColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PARTY
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String party;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PARTY_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String partyCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.SALES_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String salesNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.SALES_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String salesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String qdfBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String qdfChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BYZD1
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BYZD2
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BYZD3
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.OPER_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String cbsActSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String chkActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.BANK_TAKE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String bankTake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.CALL_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String callDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.NODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PAY_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String uploadRltFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String uploadRltDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String printTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PRINT_OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String printOperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.ORG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String org;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_TICKET_INFO.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    private String preActSerial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PKID
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PKID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PKID
     *
     * @param pkid the value for FIS.FS_LTF_TICKET_INFO.PKID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BANK_CODE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BANK_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BANK_CODE
     *
     * @param bankCode the value for FIS.FS_LTF_TICKET_INFO.BANK_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.ORDER_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.ORDER_NO
     *
     * @param orderNo the value for FIS.FS_LTF_TICKET_INFO.ORDER_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.TRANS_TIME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.TRANS_TIME
     *
     * @param transTime the value for FIS.FS_LTF_TICKET_INFO.TRANS_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setTransTime(String transTime) {
        this.transTime = transTime == null ? null : transTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.AMOUNT
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.AMOUNT
     *
     * @param amount the value for FIS.FS_LTF_TICKET_INFO.AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.OVERDUE_FINE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public BigDecimal getOverdueFine() {
        return overdueFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.OVERDUE_FINE
     *
     * @param overdueFine the value for FIS.FS_LTF_TICKET_INFO.OVERDUE_FINE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOverdueFine(BigDecimal overdueFine) {
        this.overdueFine = overdueFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BUS_CODE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BUS_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getBusCode() {
        return busCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BUS_CODE
     *
     * @param busCode the value for FIS.FS_LTF_TICKET_INFO.BUS_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setBusCode(String busCode) {
        this.busCode = busCode == null ? null : busCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.ORDER_CHARGES
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOrderCharges() {
        return orderCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.ORDER_CHARGES
     *
     * @param orderCharges the value for FIS.FS_LTF_TICKET_INFO.ORDER_CHARGES
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOrderCharges(String orderCharges) {
        this.orderCharges = orderCharges == null ? null : orderCharges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.ACCOUNT_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.ACCOUNT_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.ACCOUNT_NO
     *
     * @param accountNo the value for FIS.FS_LTF_TICKET_INFO.ACCOUNT_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BILL_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BILL_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BILL_NO
     *
     * @param billNo the value for FIS.FS_LTF_TICKET_INFO.BILL_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_NO
     *
     * @param ticketNo the value for FIS.FS_LTF_TICKET_INFO.TICKET_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_TIME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_TIME
     *
     * @param ticketTime the value for FIS.FS_LTF_TICKET_INFO.TICKET_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setTicketTime(String ticketTime) {
        this.ticketTime = ticketTime == null ? null : ticketTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_AMOUNT
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.TICKET_AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public BigDecimal getTicketAmount() {
        return ticketAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.TICKET_AMOUNT
     *
     * @param ticketAmount the value for FIS.FS_LTF_TICKET_INFO.TICKET_AMOUNT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setTicketAmount(BigDecimal ticketAmount) {
        this.ticketAmount = ticketAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PAYER_NAME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PAYER_NAME
     *
     * @param payerName the value for FIS.FS_LTF_TICKET_INFO.PAYER_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.ID_CARD
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.ID_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.ID_CARD
     *
     * @param idCard the value for FIS.FS_LTF_TICKET_INFO.ID_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PHONE_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PHONE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PHONE_NO
     *
     * @param phoneNo the value for FIS.FS_LTF_TICKET_INFO.PHONE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.HANDLE_DEPT
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.HANDLE_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getHandleDept() {
        return handleDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.HANDLE_DEPT
     *
     * @param handleDept the value for FIS.FS_LTF_TICKET_INFO.HANDLE_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setHandleDept(String handleDept) {
        this.handleDept = handleDept == null ? null : handleDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.DRIVE_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getDriveNo() {
        return driveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.DRIVE_NO
     *
     * @param driveNo the value for FIS.FS_LTF_TICKET_INFO.DRIVE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setDriveNo(String driveNo) {
        this.driveNo = driveNo == null ? null : driveNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.RUN_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.RUN_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getRunNo() {
        return runNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.RUN_NO
     *
     * @param runNo the value for FIS.FS_LTF_TICKET_INFO.RUN_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setRunNo(String runNo) {
        this.runNo = runNo == null ? null : runNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PLATE_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PLATE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PLATE_NO
     *
     * @param plateNo the value for FIS.FS_LTF_TICKET_INFO.PLATE_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PLATE_COLOR
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PLATE_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPlateColor() {
        return plateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PLATE_COLOR
     *
     * @param plateColor the value for FIS.FS_LTF_TICKET_INFO.PLATE_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPlateColor(String plateColor) {
        this.plateColor = plateColor == null ? null : plateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.CAR_TYPE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.CAR_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.CAR_TYPE
     *
     * @param carType the value for FIS.FS_LTF_TICKET_INFO.CAR_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.CAR_COLOR
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.CAR_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.CAR_COLOR
     *
     * @param carColor the value for FIS.FS_LTF_TICKET_INFO.CAR_COLOR
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PARTY
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PARTY
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PARTY
     *
     * @param party the value for FIS.FS_LTF_TICKET_INFO.PARTY
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PARTY_CARD
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PARTY_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPartyCard() {
        return partyCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PARTY_CARD
     *
     * @param partyCard the value for FIS.FS_LTF_TICKET_INFO.PARTY_CARD
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPartyCard(String partyCard) {
        this.partyCard = partyCard == null ? null : partyCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.SALES_NO
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.SALES_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getSalesNo() {
        return salesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.SALES_NO
     *
     * @param salesNo the value for FIS.FS_LTF_TICKET_INFO.SALES_NO
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setSalesNo(String salesNo) {
        this.salesNo = salesNo == null ? null : salesNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.SALES_NAME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.SALES_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getSalesName() {
        return salesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.SALES_NAME
     *
     * @param salesName the value for FIS.FS_LTF_TICKET_INFO.SALES_NAME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setSalesName(String salesName) {
        this.salesName = salesName == null ? null : salesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_LTF_TICKET_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_LTF_TICKET_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.QDF_BOOK_FLAG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getQdfBookFlag() {
        return qdfBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.QDF_BOOK_FLAG
     *
     * @param qdfBookFlag the value for FIS.FS_LTF_TICKET_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setQdfBookFlag(String qdfBookFlag) {
        this.qdfBookFlag = qdfBookFlag == null ? null : qdfBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.QDF_CHK_FLAG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getQdfChkFlag() {
        return qdfChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.QDF_CHK_FLAG
     *
     * @param qdfChkFlag the value for FIS.FS_LTF_TICKET_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setQdfChkFlag(String qdfChkFlag) {
        this.qdfChkFlag = qdfChkFlag == null ? null : qdfChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD1
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BYZD1
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD1
     *
     * @param byzd1 the value for FIS.FS_LTF_TICKET_INFO.BYZD1
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD2
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BYZD2
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD2
     *
     * @param byzd2 the value for FIS.FS_LTF_TICKET_INFO.BYZD2
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD3
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BYZD3
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BYZD3
     *
     * @param byzd3 the value for FIS.FS_LTF_TICKET_INFO.BYZD3
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.OPER_DATE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.OPER_DATE
     *
     * @param operDate the value for FIS.FS_LTF_TICKET_INFO.OPER_DATE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.OPER_TIME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.OPER_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.OPER_TIME
     *
     * @param operTime the value for FIS.FS_LTF_TICKET_INFO.OPER_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BRANCH_ID
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BRANCH_ID
     *
     * @param branchId the value for FIS.FS_LTF_TICKET_INFO.BRANCH_ID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.OPERID
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.OPERID
     *
     * @param operid the value for FIS.FS_LTF_TICKET_INFO.OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.CBS_ACT_SERIAL
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getCbsActSerial() {
        return cbsActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.CBS_ACT_SERIAL
     *
     * @param cbsActSerial the value for FIS.FS_LTF_TICKET_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setCbsActSerial(String cbsActSerial) {
        this.cbsActSerial = cbsActSerial == null ? null : cbsActSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.CHK_ACT_DT
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getChkActDt() {
        return chkActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.CHK_ACT_DT
     *
     * @param chkActDt the value for FIS.FS_LTF_TICKET_INFO.CHK_ACT_DT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setChkActDt(String chkActDt) {
        this.chkActDt = chkActDt == null ? null : chkActDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.BANK_TAKE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.BANK_TAKE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getBankTake() {
        return bankTake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.BANK_TAKE
     *
     * @param bankTake the value for FIS.FS_LTF_TICKET_INFO.BANK_TAKE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setBankTake(String bankTake) {
        this.bankTake = bankTake == null ? null : bankTake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.CALL_DEPT
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.CALL_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getCallDept() {
        return callDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.CALL_DEPT
     *
     * @param callDept the value for FIS.FS_LTF_TICKET_INFO.CALL_DEPT
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setCallDept(String callDept) {
        this.callDept = callDept == null ? null : callDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.NODE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.NODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.NODE
     *
     * @param node the value for FIS.FS_LTF_TICKET_INFO.NODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.AREA_CODE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_LTF_TICKET_INFO.AREA_CODE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PAY_TYPE
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PAY_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PAY_TYPE
     *
     * @param payType the value for FIS.FS_LTF_TICKET_INFO.PAY_TYPE
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_FLAG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getUploadRltFlag() {
        return uploadRltFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_FLAG
     *
     * @param uploadRltFlag the value for FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_FLAG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setUploadRltFlag(String uploadRltFlag) {
        this.uploadRltFlag = uploadRltFlag == null ? null : uploadRltFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_DESC
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getUploadRltDesc() {
        return uploadRltDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_DESC
     *
     * @param uploadRltDesc the value for FIS.FS_LTF_TICKET_INFO.UPLOAD_RLT_DESC
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setUploadRltDesc(String uploadRltDesc) {
        this.uploadRltDesc = uploadRltDesc == null ? null : uploadRltDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PRINT_TIME
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPrintTime() {
        return printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PRINT_TIME
     *
     * @param printTime the value for FIS.FS_LTF_TICKET_INFO.PRINT_TIME
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPrintTime(String printTime) {
        this.printTime = printTime == null ? null : printTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PRINT_OPERID
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PRINT_OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPrintOperid() {
        return printOperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PRINT_OPERID
     *
     * @param printOperid the value for FIS.FS_LTF_TICKET_INFO.PRINT_OPERID
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPrintOperid(String printOperid) {
        this.printOperid = printOperid == null ? null : printOperid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.ORG
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.ORG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.ORG
     *
     * @param org the value for FIS.FS_LTF_TICKET_INFO.ORG
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setOrg(String org) {
        this.org = org == null ? null : org.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_TICKET_INFO.PRE_ACT_SERIAL
     *
     * @return the value of FIS.FS_LTF_TICKET_INFO.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public String getPreActSerial() {
        return preActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_TICKET_INFO.PRE_ACT_SERIAL
     *
     * @param preActSerial the value for FIS.FS_LTF_TICKET_INFO.PRE_ACT_SERIAL
     *
     * @mbggenerated Tue Mar 27 16:03:20 CST 2018
     */
    public void setPreActSerial(String preActSerial) {
        this.preActSerial = preActSerial == null ? null : preActSerial.trim();
    }
}