package org.fbi.ltf.repository.model;

import java.math.BigDecimal;

public class FsLtfVchOutItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.PKID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_CODE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_NAME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.AMOUNT
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.TICKET_NO
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String ticketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.INFO_ID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD1
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD2
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD3
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_DATE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_TIME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    private String operTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.PKID
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.PKID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.PKID
     *
     * @param pkid the value for FIS.FS_LTF_VCH_OUT_ITEM.PKID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_CODE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.ITEM_CODE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_CODE
     *
     * @param itemCode the value for FIS.FS_LTF_VCH_OUT_ITEM.ITEM_CODE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_NAME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.ITEM_NAME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.ITEM_NAME
     *
     * @param itemName the value for FIS.FS_LTF_VCH_OUT_ITEM.ITEM_NAME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.AMOUNT
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.AMOUNT
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.AMOUNT
     *
     * @param amount the value for FIS.FS_LTF_VCH_OUT_ITEM.AMOUNT
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.TICKET_NO
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.TICKET_NO
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.TICKET_NO
     *
     * @param ticketNo the value for FIS.FS_LTF_VCH_OUT_ITEM.TICKET_NO
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.INFO_ID
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.INFO_ID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.INFO_ID
     *
     * @param infoId the value for FIS.FS_LTF_VCH_OUT_ITEM.INFO_ID
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD1
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.BYZD1
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD1
     *
     * @param byzd1 the value for FIS.FS_LTF_VCH_OUT_ITEM.BYZD1
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD2
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.BYZD2
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD2
     *
     * @param byzd2 the value for FIS.FS_LTF_VCH_OUT_ITEM.BYZD2
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD3
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.BYZD3
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.BYZD3
     *
     * @param byzd3 the value for FIS.FS_LTF_VCH_OUT_ITEM.BYZD3
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_DATE
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.OPER_DATE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_DATE
     *
     * @param operDate the value for FIS.FS_LTF_VCH_OUT_ITEM.OPER_DATE
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_TIME
     *
     * @return the value of FIS.FS_LTF_VCH_OUT_ITEM.OPER_TIME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_LTF_VCH_OUT_ITEM.OPER_TIME
     *
     * @param operTime the value for FIS.FS_LTF_VCH_OUT_ITEM.OPER_TIME
     *
     * @mbggenerated Wed Apr 11 17:49:28 CST 2018
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }
}