package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfSysClt;
import org.fbi.ltf.repository.model.FsLtfSysCltExample;

public interface FsLtfSysCltMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int countByExample(FsLtfSysCltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int deleteByExample(FsLtfSysCltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int insert(FsLtfSysClt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int insertSelective(FsLtfSysClt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    List<FsLtfSysClt> selectByExample(FsLtfSysCltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    FsLtfSysClt selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") FsLtfSysClt record, @Param("example") FsLtfSysCltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int updateByExample(@Param("record") FsLtfSysClt record, @Param("example") FsLtfSysCltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int updateByPrimaryKeySelective(FsLtfSysClt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_SYS_CLT
     *
     * @mbggenerated Mon Mar 19 10:19:35 CST 2018
     */
    int updateByPrimaryKey(FsLtfSysClt record);
}