package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfAcctFile;
import org.fbi.ltf.repository.model.FsLtfAcctFileExample;

public interface FsLtfAcctFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int countByExample(FsLtfAcctFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int deleteByExample(FsLtfAcctFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int insert(FsLtfAcctFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int insertSelective(FsLtfAcctFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    List<FsLtfAcctFile> selectByExample(FsLtfAcctFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    FsLtfAcctFile selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") FsLtfAcctFile record, @Param("example") FsLtfAcctFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByExample(@Param("record") FsLtfAcctFile record, @Param("example") FsLtfAcctFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByPrimaryKeySelective(FsLtfAcctFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_FILE
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByPrimaryKey(FsLtfAcctFile record);
}