package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfAcctInfo;
import org.fbi.ltf.repository.model.FsLtfAcctInfoExample;
import org.fbi.ltf.repository.model.FsLtfAcctInfoKey;

public interface FsLtfAcctInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int countByExample(FsLtfAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int deleteByExample(FsLtfAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int deleteByPrimaryKey(FsLtfAcctInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int insert(FsLtfAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int insertSelective(FsLtfAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    List<FsLtfAcctInfo> selectByExample(FsLtfAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    FsLtfAcctInfo selectByPrimaryKey(FsLtfAcctInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") FsLtfAcctInfo record, @Param("example") FsLtfAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByExample(@Param("record") FsLtfAcctInfo record, @Param("example") FsLtfAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByPrimaryKeySelective(FsLtfAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ACCT_INFO
     *
     * @mbggenerated Mon Dec 21 11:10:50 CST 2015
     */
    int updateByPrimaryKey(FsLtfAcctInfo record);
}