package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfPoliceOrgComp;
import org.fbi.ltf.repository.model.FsLtfPoliceOrgCompExample;

public interface FsLtfPoliceOrgCompMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int countByExample(FsLtfPoliceOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int deleteByExample(FsLtfPoliceOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int deleteByPrimaryKey(String orgCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int insert(FsLtfPoliceOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int insertSelective(FsLtfPoliceOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    List<FsLtfPoliceOrgComp> selectByExample(FsLtfPoliceOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    FsLtfPoliceOrgComp selectByPrimaryKey(String orgCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") FsLtfPoliceOrgComp record, @Param("example") FsLtfPoliceOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int updateByExample(@Param("record") FsLtfPoliceOrgComp record, @Param("example") FsLtfPoliceOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int updateByPrimaryKeySelective(FsLtfPoliceOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_POLICE_ORG_COMP
     *
     * @mbggenerated Sun Jan 24 16:57:56 CST 2016
     */
    int updateByPrimaryKey(FsLtfPoliceOrgComp record);
}