package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfOrgComp;
import org.fbi.ltf.repository.model.FsLtfOrgCompExample;

public interface FsLtfOrgCompMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int countByExample(FsLtfOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int deleteByExample(FsLtfOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int deleteByPrimaryKey(String orgCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int insert(FsLtfOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int insertSelective(FsLtfOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    List<FsLtfOrgComp> selectByExample(FsLtfOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    FsLtfOrgComp selectByPrimaryKey(String orgCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") FsLtfOrgComp record, @Param("example") FsLtfOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int updateByExample(@Param("record") FsLtfOrgComp record, @Param("example") FsLtfOrgCompExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int updateByPrimaryKeySelective(FsLtfOrgComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_ORG_COMP
     *
     * @mbggenerated Wed Dec 16 21:45:05 CST 2015
     */
    int updateByPrimaryKey(FsLtfOrgComp record);
}