package org.fbi.ltf.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.ltf.repository.model.FsLtfVchOutItem;
import org.fbi.ltf.repository.model.FsLtfVchOutItemExample;

public interface FsLtfVchOutItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int countByExample(FsLtfVchOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int deleteByExample(FsLtfVchOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int insert(FsLtfVchOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int insertSelective(FsLtfVchOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    List<FsLtfVchOutItem> selectByExample(FsLtfVchOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    FsLtfVchOutItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") FsLtfVchOutItem record, @Param("example") FsLtfVchOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int updateByExample(@Param("record") FsLtfVchOutItem record, @Param("example") FsLtfVchOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int updateByPrimaryKeySelective(FsLtfVchOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_LTF_VCH_OUT_ITEM
     *
     * @mbggenerated Wed Dec 09 22:01:28 CST 2015
     */
    int updateByPrimaryKey(FsLtfVchOutItem record);
}